### ISSUE TITLE
[BUG] devDependencies are declared as dependencies

### ISSUE THREAD

**Issue by NicolasCARPi** [3dmol/3Dmol.js#649]
**Describe the bug**
Hello,

The package.json lists dependencies that should really be devDependencies.

For instance, `npm` should not be a dependency of this package. I am not sure about the others, but if they are not strictly required for the prod build to work, they should move to devDependencies.

**To Reproduce**

Install the package with npm or yarn.

**Expected behavior**
The package doesn't add 1437 lines in lockfile because it pulls _many_ dependencies that should only be pulled in CI.

Unrelated note: congratulations on removing jQuery dependency!

**Comment by dkoes** [comment]
Taking @adithyaakrishna's advice and moving this to engines.

**Comment by NicolasCARPi** [comment]
@dkoes Are you planning a patch release with this change soon?

**Comment by dkoes** [comment]
Sure - 2.0.2 is now published.

**Comment by NicolasCARPi** [comment]
Great, thanks!

**Comment by dkoes** [comment]
Hadn't crossed my mind, but is a logical thing to do when a release is created.

**Comment by NicolasCARPi** [comment]
> There will be a manual trigger on the Actions UI, and if run, it auto publishes to npm

I suggest doing it automatically on new release action. Here is an example: https://github.com/deltablot/malle/blob/master/.github/workflows/publishing.yml

**Comment by dkoes** [comment]
Thanks - we'll see if works next release.

**Comment by adithyaakrishna** [comment]
I feel we can add another workflow trigger, so the yml file becomes

```yaml
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
```
